### ISSUE TITLE
osgEarth broken on yosemite 

### ISSUE THREAD

**Issue by febret** [omega-hub/omegaOsgEarth#6]
Aven after setting DYLD_LIBRARY_DIR to the omegalib bin dir, omegaOsgEarth still fails

**Comment by febret** [comment]
Verified on a 2013 mac mini
![picture](https://cloud.githubusercontent.com/assets/4543642/6306432/2eddddfa-b8f9-11e4-87b2-3924bd122d05.jpeg)

**Comment by febret** [comment]
-> GL Copatibility profile returns shader version 1.2
- may be a problem with XQuartz/GL context?
tried enabling EQUALIZER_PREFER_AGL but eq still wants to use X. See if this is easy to solve and
if going to AGL takes care of other problems (additional good side-effect = no more need for xQuartZ)

**Comment by mvictoras** [comment]
The version of osgEarth that I was working with could only use X. I think
it was a problem with Equalizer, not osgEarth.
I remember compiling all the modules with X instead of AGL, so if Equalizer
works, osgEarth should work as well.


On Mon, Feb 23, 2015 at 11:59 AM, Alessandro Febretti <
notifications@github.com> wrote:

> -> GL Copatibility profile returns shader version 1.2
>
>    - may be a problem with XQuartz/GL context? tried enabling
>    EQUALIZER_PREFER_AGL but eq still wants to use X. See if this is easy to
>    solve and if going to AGL takes care of other problems (additional good
>    side-effect = no more need for xQuartZ)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omega-hub/omegaOsgEarth/issues/6#issuecomment-75595573>
> .
>



-- 
*Victor Mateevitsi*
PhD Candidate - University of Illinois at Chicago <http://www.uic.edu/>
Research Assistant - Electronic Visualization Laboratory
<http://www.evl.uic.edu/>
mvictoras@gmail.com
www <http://www.vmateevitsi.com> | LinkedIn
<http://www.linkedin.com/pub/5/919/845> | Twitter
<http://twitter.com/mvictoras> | UIC <http://www.uic.edu> | EVL
<http://www.evl.uic.edu>
